from . import MCNN
from . import VGG
from . import Res101_SFCN
from . import CSRNet
from . import SCAR
from . import VGG
from . import AlexNet
from . import Res101
from . import Res50
from . import CANNet
